name: assignment_crud
description: "A Flutter assignment management app"

environment:
  sdk: '>=3.0.0 <4.0.0'

publish_to: 'none'

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  fl_chart: ^0.66.0
  flutter_local_notifications: ^16.3.0
  table_calendar: ^3.0.9
  file_picker: ^5.5.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true